services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8010:80'
      - '443:443'
    volumes:
      - './config/index.html:/var/www/html/index.html'
      - './config/nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - test_client
    networks:
      - front_tier
    restart: always
  test_client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: test_client_container
    hostname: test_client_host
    ports:
      - '3010:5173'
    env_file:
      - ./client/.env
    networks:
      - front_tier
    restart: always

networks:
  front_tier:
