services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '90:90'
      - '450:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - test_client
    networks:
      - test_front_tier
    restart: always
  test_client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: test_client_container
    hostname: test_client_host
    ports:
      - '3005:5173'
    env_file:
      - ./client/.env
    networks:
      - test_front_tier
    restart: always

networks:
  test_front_tier:
